const e=id=>document.getElementById(id),money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0));function clock(){e('clock').textContent=new Date().toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}async function refresh(){try{const [s,h]=await Promise.all([fetch('/api/status',{cache:'no-store'}),fetch('/health',{cache:'no-store'})]);if(!s.ok||!h.ok)throw 0;const d=await s.json(),x=await h.json(),t=d.totals||{};e('robots').textContent=Math.max(1,t.robots||0)+' / '+Math.max(1,t.robots||0);e('sales').textContent=t.sales||0;e('gross').textContent=money(t.gross);e('commission').textContent=money(t.commission);e('generalCommission').textContent=money(t.commission);e('balance').textContent=money(t.balance);e('transferred').textContent=money(t.transferred);e('robotSales').textContent=t.sales||0;e('robotCommission').textContent=money(t.commission);e('apiHotmart').textContent=x.hotmart_api_configured?'Online':'Configuração pendente';e('server').textContent='Online'}catch(_){e('server').textContent='Indisponível';e('apiHotmart').textContent='Verificar'}}clock();setInterval(clock,1000);refresh();setInterval(refresh,5000);
function showView(view){['finance','social','robots'].forEach(v=>e(v+'View').classList.toggle('hidden',v!==view));document.querySelectorAll('aside nav [data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===view));document.querySelectorAll('.topnav [data-topview]').forEach(x=>x.classList.toggle('active',x.dataset.topview===view));if(view==='social')refreshSocial();if(view==='robots')refreshRobots()}
document.querySelectorAll('aside nav [data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));document.querySelectorAll('.topnav [data-topview]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.topview)));
async function refreshSocial(){try{const [c,o]=await Promise.all([fetch('/api/commercial',{cache:'no-store'}),fetch('/api/offers',{cache:'no-store'})]);if(!c.ok||!o.ok)throw 0;const commercial=await c.json(),offers=await o.json(),rank=commercial.ranking||[];const clicksBy={};rank.forEach(r=>{clicksBy[r.id]=Number(r.clicks||0)});e('activeOffers').textContent=commercial.active_offers||0;const channelTotals={TikTok:0,Instagram:0,Facebook:0};const total=Number(commercial.clicks||0);e('ttClicks').textContent='—';e('igClicks').textContent='—';e('fbClicks').textContent='—';e('networkRows').innerHTML='<div class="networkRow"><span>Total rastreado pelo WERO1</span><strong>'+total+' cliques</strong><span>'+Number(commercial.confirmed_sales||0)+' vendas confirmadas</span></div><div class="networkRow"><span>Conversão global</span><strong>'+Number(commercial.conversion_pct||0).toFixed(2)+'%</strong><span>Somente dados confirmados</span></div>';e('offerLinks').innerHTML=(offers.offers||[]).filter(x=>x.active).map(x=>'<div class="offerRow"><b>ID '+x.id+' — '+x.product_name+'</b><a href="/go/'+x.id+'?channel=social&campaign=dashboard&robot_id=WERO1-PAI" target="_blank">/go/'+x.id+'</a><span>'+Number(clicksBy[x.id]||0)+' cliques</span></div>').join('')||'Nenhuma oferta ativa'}catch(_){e('networkRows').textContent='Dados sociais indisponíveis';e('offerLinks').textContent='Não foi possível carregar as ofertas'}}
async function refreshRobots(){try{const r=await fetch('/api/status',{cache:'no-store'});if(!r.ok)throw 0;const d=await r.json(),rows=d.robots||[],t=d.totals||{};e('robotTotal').textContent=rows.length;e('robotActive').textContent=rows.length;e('robotTotalSales').textContent=Number(t.sales||0);e('robotTotalCommission').textContent=money(t.commission);e('robotRows').innerHTML=rows.map(x=>'<div class="robotDataRow"><b>'+esc(x.robot_id||'Sem ID')+'</b><span>'+hierarchy(x.robot_id)+'</span><span class="ok">● Atividade confirmada</span><span>'+Number(x.sales||0)+'</span><span>'+money(x.commission)+'</span><span>'+fmtTime(x.last_event)+'</span></div>').join('')||'<div class="empty">Nenhum robô com atividade financeira confirmada ainda.</div>'}catch(_){e('robotRows').textContent='Status dos robôs indisponível'}}
function hierarchy(id){const x=String(id||'').toLowerCase();return x.includes('filho')?'FILHO':'PAI'}
function fmtTime(v){if(!v)return 'Sem evento confirmado';const d=new Date(v);return isNaN(d)?String(v):d.toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}
function esc(v){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}

function gaugeAngle(value,max){const n=Math.max(0,Math.min(Number(value)||0,max));return -90+(n/max)*180}
function setNeedle(id,value,max){const n=e(id);if(n)n.style.transform='rotate('+gaugeAngle(value,max)+'deg)'}
async function refreshPressure(){try{const [p,s]=await Promise.all([fetch('/api/performance',{cache:'no-store'}),fetch('/api/status',{cache:'no-store'})]);if(!p.ok)throw 0;const d=await p.json(),st=s.ok?await s.json():{},t=st.totals||{},rps=Number(d.requests_per_second||0),lat=Number(d.latency_ms_ema||0),errs=Number(d.errors||0),sales=Number(t.sales||0);e('pressureMode').textContent='MODO '+String(d.mode||'game').toUpperCase();e('activityValue').textContent=rps.toFixed(2);e('latencyValue').textContent=lat.toFixed(0);e('errorValue').textContent=errs;e('salesPressureValue').textContent=sales;setNeedle('activityNeedle',rps,10);setNeedle('latencyNeedle',lat,1000);setNeedle('errorNeedle',errs,20);setNeedle('salesNeedle',sales,20);e('activityState').textContent=rps>0?'Motor em movimento':'Motor em espera';e('latencyState').textContent=lat<250?'Resposta rápida':lat<600?'Resposta moderada':'Resposta sob pressão';e('errorState').textContent=errs===0?'Sem falhas registradas':'Falhas registradas: '+errs}catch(_){['activityState','latencyState','errorState'].forEach(id=>{if(e(id))e(id).textContent='Telemetria indisponível'})}}
refreshPressure();setInterval(refreshPressure,2000);
